version: '3.9'
services:

  pg:
    image: postgres:16.4
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
#      - ./scripts/ddl.sql:/docker-entrypoint-initdb.d/1.sql # Create data model
      - ./scripts/partitions/ddl.sql:/docker-entrypoint-initdb.d/1.sql # Create data model with partitions
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql # Fill data
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
    driver: bridge